version: '3'
services:
  mysqldb:
    image: mysql5.5
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=jjjjjj
    ports: 
      - "3306:3306"
    volumes:
        - ./data/db/mysql:/var/lib/mysql
        - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf