version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/cert:/etc/nginx/cert
      - ./data/logs:/var/log/nginx
      - /data/dockers/blogOfAllen/data:/data/blogOfAllen