version: '3'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/snaplingo/nginx:1.13-alpine
    restart: always
    ports:
      - "1000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./cert:/etc/nginx/cert
      - ./logs:/var/log/nginx
      - ./code:/data/code
